server_api:
  secure: false
  host: localhost
  port: 8080

server_web:
  secure: false
  host: localhost
  port: 8181

storage:
  type: filesystem # or s3

dirpaths:
  upload: /tmp/hansip-files/uploaded
  bundle: /tmp/hansip-files/bundled

database:
  host: localhost
  port: 5432
  name: your_dbname
  user: your_dbusername
  password: your_dbpassword

short_id:
  worker: 1
  seed: 7357

aws:
  region:
  s3:
    bucket_name:
    access_key:
    secret_key:
