# Set host & port for hansip backend server
server_api:
  secure: false # set true if the address is https
  host: localhost
  port: 8080

# Set host & port for web application server
server_web:
  secure: false # set true if the address is https
  host: localhost
  port: 8181

storage:
  type: filesystem # or s3

dirpaths:
  # Directory when uploading files before processed 
  upload: ./hansip-files/uploaded
  # Directory for storing files after processed,
  # files on bundle directory will be removed if activates S3 after successfully uploaded
  bundle: ./hansip-files/bundled

db:
  type: sqlite # or postgresql

sqlite:
  # path for sqlite database file
  # by default will use WAL mode for better concurrency
  path: ./hansip.db

postgresql:
  host: localhost
  port: 5432
  name: your_dbname
  user: your_dbusername
  password: your_dbpassword

short_id:
  worker: 1
  seed: 7357

aws:
  region:
  s3:
    bucket_name:
    access_key:
    secret_key:
